import Modal from '../js/components/modal/index.vue';

export default {
  title: 'Example/Modal',
  component: Modal,
  argTypes: {
    iconsName: {
      control: {
        type: 'select',
        options: [
          'chevron-right-Pagination',
          'chevron-left-Pagination',
          'Circle-arrow-badge',
          'Difference-badge',
          'in-pay-badge',
          'multiplied-by-badge',
          'sent-to-shapparak-badge',
          'Tick-badge',
          'info-line',
          'phonelink',
          'account_tree',
          'logout',
          'setting-line',
          'all-dashboard',
          'export',
          'arrow-down-sort',
          'arrow-up-sort',
          'filter',
          'html',
          'pdf',
          'coupon_border',
          'money-24px',
          'receipt',
          'check-nopadding',
          'tasviye-shaparak-nopadding',
          'outline-receipt-noborder',
          'product',
          'tour-guide',
          'handle',
          'cancel',
          'add-round',
          'list',
          'notification-outline',
          'store',
          'back',
          'back-long',
          'arrow-drop-down',
          'round-link-24px',
          'warning',
          'info',
          'error',
          'terminal',
          'upload',
          'current',
          'done',
          'double-arrow',
          'pending',
          'check',
          'up',
          'down',
          'sync',
          'shetabi',
          'cards2',
          'coupon',
          'zarinlink',
          'power',
          'session',
          'setting',
          'today',
          'track',
          'outline-receipt',
          'email',
          'arrow-down',
          'print',
          'add',
          'close',
          'excel',
          'attach',
          'mail',
          'mail-open',
          'copy',
          'delete',
          'edit',
          'code',
          'view',
          'card',
          'doc',
          'invite',
          'link',
          'telegram',
          'arrow-right',
          'cards',
          'logo',
          'mobile',
          'document',
          'qr',
          'home',
          'money',
          'knowledge',
          'drop-down',
          'menu',
          'notification',
          'search',
          'help',
          'user-outline'
        ],
      },
    },
    size: { control: { type: 'select', options: ['small', 'medium', 'large'] } },
  },

};

const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { Modal },
  template: '<Modal   v-bind="$props" />',
});

export const blue = Template.bind({});
blue.args = {
  blue: true,
  iconsName:'notification-outline',
  title: 'نمونه متن برای عنوان ',
  buttonAction: 'ذخیره ',
  headingModal: 'نمایش مودال ',
  buttonSecondaryAction: 'پاک کردن ',

};
export const remove = Template.bind({});
remove.args = {
  remove: true,
  title: 'حذف زرین‌لینک ',
  iconsName:'delete',

  headingModal: 'نمایش مودال حذف ',
  buttonAction: 'حذف ',
  buttonSecondaryAction: 'انصراف ',
  content: 'ازحذف این آیتم مطمینید؟  ',

};
export const green = Template.bind({});
green.args = {
  green: true,
  title: 'نمونه متن برای عنوان ',
  buttonAction: 'ذخیره ',
  headingModal: 'نمایش مودال ',
  buttonSecondaryAction: 'پاک کردن ',

};

